import ChatMessage from '@/components/bot/message/chat-message';
import { useAuth } from '@/context/auth-context';
import { useChatHistory } from '@/hooks/meditalk/use-chathistory';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import React, { useCallback, useEffect, useRef, useState } from 'react';
import {
  Alert,
  Animated,
  Keyboard,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  Text,
  TextInput,
  TouchableOpacity,
  View
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

export default function HealthBotScreen() {
  const { user } = useAuth();
  const insets = useSafeAreaInsets();
  const scrollViewRef = useRef<ScrollView>(null);
  const [isSending, setIsSending] = useState(false);

  const { saveConversation, loadRecentMessages, loadHistory } = useChatHistory();

  const [messages, setMessages] = useState<any[]>([]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [streamingMessageId, setStreamingMessageId] = useState<string | null>(null);
  const pulseAnim = useRef(new Animated.Value(1)).current;

  // Pulse animation for loading dots
  useEffect(() => {
    if (isLoading) {
      Animated.loop(
        Animated.sequence([
          Animated.timing(pulseAnim, {
            toValue: 0.5,
            duration: 500,
            useNativeDriver: true,
          }),
          Animated.timing(pulseAnim, {
            toValue: 1,
            duration: 500,
            useNativeDriver: true,
          }),
        ])
      ).start();
    } else {
      pulseAnim.setValue(1);
    }
  }, [isLoading]);

  const scrollToBottom = () => {
    setTimeout(() => {
      scrollViewRef.current?.scrollToEnd({ animated: true });
    }, 100);
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  // Scroll when keyboard opens
  useEffect(() => {
    const showSub = Keyboard.addListener('keyboardDidShow', scrollToBottom);
    return () => showSub.remove();
  }, []);

  // Load history on mount
  useEffect(() => {
    const loadchats = async () => {
      if (!user) return;
      try {
        const history = await loadHistory({ orderBy: "asc"});
        const formatted = history.map(msg => ({
          id: msg.id,
          role: msg.role,
          content: msg.content,
          timestamp: msg.timestamp,
        }));
        setMessages(formatted);
      } catch (error) {
        console.error('Error loading history:', error);
      }
    };
    loadchats();
  }, [user]);

  const downloadPDF = async (message: any) => {
    try {
      const html = `
        <html>
          <head>
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
                padding: 40px;
                line-height: 1.6;
                color: #333;
              }
              h1 { color: #2563eb; font-size: 24px; }
              h2 { color: #1e40af; font-size: 20px; margin-top: 20px; }
              code {
                background: #f3f4f6;
                padding: 2px 6px;
                border-radius: 4px;
              }
              pre {
                background: #1f2937;
                color: #e5e7eb;
                padding: 12px;
                border-radius: 8px;
                overflow-x: auto;
              }
              table {
                border-collapse: collapse;
                width: 100%;
                margin: 16px 0;
              }
              th, td {
                border: 1px solid #e5e7eb;
                padding: 8px 12px;
              }
              th {
                background: #f3f4f6;
              }
            </style>
          </head>
          <body>
            ${message.content}
            <hr style="margin-top: 40px;" />
            <p style="font-size: 12px; color: #9ca3af; text-align: center;">
              Generated by Meditalk on ${new Date().toLocaleString()}
            </p>
          </body>
        </html>
      `;
      
      const { uri } = await Print.printToFileAsync({ html });
      await Sharing.shareAsync(uri);
    } catch (error) {
      console.error('Error generating PDF:', error);
      Alert.alert('Error', 'Failed to generate PDF');
    }
  };

  const handleSend = useCallback(async () => {
    if (!input.trim() || !user || isSending) return;

    const userText = input.trim();
    const userMsg = {
      id: Date.now().toString(),
      role: 'user',
      content: userText,
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setIsLoading(true);
    setIsSending(true);

    const assistantId = (Date.now() + 1).toString();
    setStreamingMessageId(assistantId);
    
    // Add placeholder message for streaming
    setMessages(prev => [
      ...prev,
      {
        id: assistantId,
        role: 'assistant',
        content: '',
        timestamp: new Date(),
      },
    ]);

    try {
      const apiMessages = [...messages, userMsg].map(m => ({
        role: m.role,
        content: m.content,
      }));

      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: apiMessages,
          userId: user.uid,
          model: 'gpt-4o',
        }),
      });

      if (!response.ok) {
        throw new Error(`API error: ${response.status}`);
      }

      const data = await response.json();
      const assistantText = data.text || 'No response';

      // Update the streaming message with full content
      setMessages(prev =>
        prev.map(msg =>
          msg.id === assistantId
            ? { ...msg, content: assistantText }
            : msg
        )
      );

      await saveConversation(userText, assistantText, {
        model: 'gpt-4o',
        processingTime: 0,
        tokens: Math.ceil((userText.length + assistantText.length) / 4),
      });

    } catch (error) {
      console.error('Chat error:', error);
      setMessages(prev =>
        prev.map(msg =>
          msg.id === assistantId
            ? { ...msg, content: 'Sorry, I encountered an error. Please try again.' }
            : msg
        )
      );
    } finally {
      setIsLoading(false);
      setIsSending(false);
      setStreamingMessageId(null);
    }
  }, [input, user, messages, isSending]);

  // Loading dots component
  const LoadingDots = () => (
    <View className="flex-row justify-start mb-4">
      <View className="flex-row items-center gap-1 bg-neutral-800/50 rounded-full px-4 py-2">
        <Animated.View
          style={{
            width: 8,
            height: 8,
            borderRadius: 4,
            backgroundColor: '#3b82f6',
            transform: [{ scale: pulseAnim }],
          }}
        />
        <Animated.View
          style={{
            width: 8,
            height: 8,
            borderRadius: 4,
            backgroundColor: '#3b82f6',
            transform: [{ scale: pulseAnim }],
            opacity: 0.7,
          }}
        />
        <Animated.View
          style={{
            width: 8,
            height: 8,
            borderRadius: 4,
            backgroundColor: '#3b82f6',
            transform: [{ scale: pulseAnim }],
            opacity: 0.4,
          }}
        />
      </View>
    </View>
  );

  return (
    <KeyboardAvoidingView
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      style={{ flex: 1, backgroundColor: 'black' }}
      keyboardVerticalOffset={90}
    >
      <ScrollView
        ref={scrollViewRef}
        style={{ flex: 1, paddingHorizontal: 16, paddingTop: 16 }}
        contentContainerStyle={{ paddingBottom: insets.bottom + 80 }}
        keyboardShouldPersistTaps="handled"
      >
        {messages.length === 0 && (
          <Text style={{ color: '#6b7280', marginBottom: 10, textAlign: 'center' }}>
            👋 Welcome to Meditalk
          </Text>
        )}

        {messages.map(msg => (
          <ChatMessage
            key={msg.id}
            message={msg}
            onDownloadPDF={downloadPDF}
            isStreaming={msg.id === streamingMessageId && msg.content === ''}
          />
        ))}

        {isLoading && !streamingMessageId && <LoadingDots />}
      </ScrollView>

      <LinearGradient
        colors={['black', 'transparent']}
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          height: 40,
          pointerEvents: 'none',
        }}
      />
      <LinearGradient
        colors={['transparent', 'black']}
        style={{
          position: 'absolute',
          bottom: 70,
          left: 0,
          right: 0,
          height: 60,
          pointerEvents: 'none',
        }}
      />

      {/* Input Bar */}
      <View
        style={{
          padding: 12,
          borderTopColor: '#1f1f1f',
          backgroundColor: 'black',
          paddingBottom: insets.bottom || 20,
        }}
      >
        <View
          style={{
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: '#191919',
            borderRadius: 30,
            paddingHorizontal: 16,
            paddingVertical: 6,
          }}
        >
          <TextInput
            value={input}
            onChangeText={setInput}
            placeholder={user ? "Message Meditalk..." : "Login required"}
            placeholderTextColor="#666"
            multiline
            style={{
              flex: 1,
              color: 'white',
              paddingVertical: 10,
              maxHeight: 100,
              fontSize: 16,
            }}
          />

          <TouchableOpacity
            onPress={handleSend}
            disabled={!input.trim() || isLoading || isSending}
            style={{
              width: 32,
              height: 32,
              borderRadius: 16,
              alignItems: 'center',
              justifyContent: 'center',
              backgroundColor: input.trim() && !isLoading ? 'white' : '#2a2a2a',
            }}
          >
            <Ionicons
              name="arrow-up"
              size={16}
              color={input.trim() && !isLoading ? 'black' : '#666'}
            />
          </TouchableOpacity>
        </View>
      </View>
    </KeyboardAvoidingView>
  );
}